global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:5000']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['book-api-cadvisor:8080']
  - job_name: 'db'
    static_configs:
      - targets: ['db']