{
 "title": "Boolfly Task",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Lượng dữ liệu gửi qua mạng",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{name=\"backend-backend-1\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Book Management API CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{name=\"backend-backend-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Book Management API Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"backend-backend-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lượng dữ liệu nhận",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=\"backend-backend-1\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}